# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Earth Workz Construction
email: amanda@earthworkzkc.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://earthworkzkc.com/" # the base hostname & protocol for your site
mobile: +1 913 927 0954
phone: +1 816 355 0280
fax: +1 816 355 0401

# Build settings
markdown: kramdown
