---
title: Earthworkz Enterprises Inc.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
emails:
- tamara@earthworkzkc.com
- zoya@earthworkzkc.com
- dustin@earthworkzkc.com
- josh@earthworkzkc.com
- jeremy@earthworkzkc.com
baseurl: ''
url: http://earthworkzkc.com/
mobile: "+1 913 927 0954"
phone: "+1 816 355 0280"
fax: "+1 816 355 0401"
address: 6950 D Highway<br> Bates City, MO 64011
markdown: kramdown
gems:
- jekyll-sitemap
